Class Demo.Messages.DrugInteractionRequestSimple Extends Ens.Request
{

Property RxCUIs As %String;

Storage Default
{
<Data name="DrugInteractionRequestSimpleDefaultData">
<Subscript>"DrugInteractionRequestSimple"</Subscript>
<Value name="1">
<Value>RxCUIs</Value>
</Value>
</Data>
<DefaultData>DrugInteractionRequestSimpleDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}

